package pe.edu.upeu.navigationjpc.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val textColor=Color(0xFF6650a4)
val Purple200=Color(0xFFEFB8C8)

val green_primaryLight = Color(0xFF4C662B)
val green_onPrimaryLight = Color(0xFFFFFFFF)
val green_primaryContainerLight = Color(0xFFCDEDA3)
val green_onPrimaryContainerLight = Color(0xFF354E16)
val green_secondaryLight = Color(0xFF586249)
val green_onSecondaryLight = Color(0xFFFFFFFF)
val green_secondaryContainerLight = Color(0xFFDCE7C8)
val green_onSecondaryContainerLight = Color(0xFF404A33)
val green_tertiaryLight = Color(0xFF386663)
val green_onTertiaryLight = Color(0xFFFFFFFF)
val green_tertiaryContainerLight = Color(0xFFBCECE7)
val green_onTertiaryContainerLight = Color(0xFF1F4E4B)
val green_errorLight = Color(0xFFBA1A1A)
val green_onErrorLight = Color(0xFFFFFFFF)
val green_errorContainerLight = Color(0xFFFFDAD6)
val green_onErrorContainerLight = Color(0xFF93000A)
val green_backgroundLight = Color(0xFFF9FAEF)
val green_onBackgroundLight = Color(0xFF1A1C16)
val green_surfaceLight = Color(0xFFF9FAEF)
val green_onSurfaceLight = Color(0xFF1A1C16)
val green_surfaceVariantLight = Color(0xFFE1E4D5)
val green_onSurfaceVariantLight = Color(0xFF44483D)
val green_outlineLight = Color(0xFF75796C)
val green_outlineVariantLight = Color(0xFFC5C8BA)
val green_scrimLight = Color(0xFF000000)
val green_inverseSurfaceLight = Color(0xFF2F312A)
val green_inverseOnSurfaceLight = Color(0xFFF1F2E6)
val green_inversePrimaryLight = Color(0xFFB1D18A)
val green_surfaceDimLight = Color(0xFFDADBD0)
val green_surfaceBrightLight = Color(0xFFF9FAEF)
val green_surfaceContainerLowestLight = Color(0xFFFFFFFF)
val green_surfaceContainerLowLight = Color(0xFFF3F4E9)
val green_surfaceContainerLight = Color(0xFFEEEFE3)
val green_surfaceContainerHighLight = Color(0xFFE8E9DE)
val green_surfaceContainerHighestLight = Color(0xFFE2E3D8)

val green_primaryDark = Color(0xFFB1D18A)
val green_onPrimaryDark = Color(0xFF1F3701)
val green_primaryContainerDark = Color(0xFF354E16)
val green_onPrimaryContainerDark = Color(0xFFCDEDA3)
val green_secondaryDark = Color(0xFFBFCBAD)
val green_onSecondaryDark = Color(0xFF2A331E)
val green_secondaryContainerDark = Color(0xFF404A33)
val green_onSecondaryContainerDark = Color(0xFFDCE7C8)
val green_tertiaryDark = Color(0xFFA0D0CB)
val green_onTertiaryDark = Color(0xFF003735)
val green_tertiaryContainerDark = Color(0xFF1F4E4B)
val green_onTertiaryContainerDark = Color(0xFFBCECE7)
val green_errorDark = Color(0xFFFFB4AB)
val green_onErrorDark = Color(0xFF690005)
val green_errorContainerDark = Color(0xFF93000A)
val green_onErrorContainerDark = Color(0xFFFFDAD6)
val green_backgroundDark = Color(0xFF12140E)
val green_onBackgroundDark = Color(0xFFE2E3D8)
val green_surfaceDark = Color(0xFF12140E)
val green_onSurfaceDark = Color(0xFFE2E3D8)
val green_surfaceVariantDark = Color(0xFF44483D)
val green_onSurfaceVariantDark = Color(0xFFC5C8BA)
val green_outlineDark = Color(0xFF8F9285)
val green_outlineVariantDark = Color(0xFF44483D)
val green_scrimDark = Color(0xFF000000)
val green_inverseSurfaceDark = Color(0xFFE2E3D8)
val green_inverseOnSurfaceDark = Color(0xFF2F312A)
val green_inversePrimaryDark = Color(0xFF4C662B)
val green_surfaceDimDark = Color(0xFF12140E)
val green_surfaceBrightDark = Color(0xFF383A32)
val green_surfaceContainerLowestDark = Color(0xFF0C0F09)
val green_surfaceContainerLowDark = Color(0xFF1A1C16)
val green_surfaceContainerDark = Color(0xFF1E201A)
val green_surfaceContainerHighDark = Color(0xFF282B24)
val green_surfaceContainerHighestDark = Color(0xFF33362E)