name: prueba
description: Front-end Flutter para listar POIs de tu backend Spring Boot.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6         # ← versión compatible con retrofit 3.x
  retrofit: ^3.0.1
  json_annotation: ^4.8.0
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.6.0
  retrofit_generator: ^4.0.1
